export const uploadFileConstants = {
    UploadFiles: {
        REQUEST: 'UPLOAD_FILE_REQUEST',
        SUCCESS: 'UPLOAD_FILE_SUCCESS',
        FAILURE: 'UPLOAD_FILE_FAILURE'
    },

    DeleteFiles: {
        REQUEST: "DELETE_FILE_REQUEST",
        SUCCESS: "DELETE_FILE_SUCCESS",
        FAILURE: "DELETE_FILE_FAILURE",
    },

    CHOOSE_FILE: "CHOOSE_FILE",
    REMOVE_FILE: "REMOVE_FILE",
    CLEAR_FILES: "CLEAR_FILES",
    CHOOSE_FILES: "CHOOSE_FILES"
}