export const orderConstants = {
  GetOrders: {
    REQUEST: 'GET_ORDERS_REQUEST',
    SUCCESS: 'GET_ORDERS_SUCCESS',
    FAILURE: 'GET_ORDERS_FAILURE'
  },

  SubmitOrder: {
    REQUEST: 'SUBMIT_ORDER_REQUEST',
    SUCCESS: 'SUBMIT_ORDER_SUCCESS',
    FAILURE: 'SUBMIT_ORDER_FAILURE'
  },

  GetStarterInfoForSubmit: {
    REQUEST: 'GET_STARTER_INFO_FOR_SUBMIT_REQUEST',
    SUCCESS: 'GET_STARTER_INFO_FOR_SUBMIT_SUCCESS',
    FAILURE: 'GET_STARTER_INFO_FOR_SUBMIT_FAILURE'
  },

  GetOrder: {
    REQUEST: 'GET_ORDER_REQUEST',
    SUCCESS: 'GET_ORDER_SUCCESS',
    FAILURE: 'GET_ORDER_FAILURE'
  },
}