export const orderConstants = {
  GetOrders: {
    REQUEST: 'GET_ORDERS_REQUEST',
    SUCCESS: 'GET_ORDERS_SUCCESS',
    FAILURE: 'GET_ORDERS_FAILURE'
  },
  GetOrderResponses: {
    REQUEST: 'GET_ORDER_RESPONSES_REQUEST',
    SUCCESS: 'GET_ORDER_RESPONSES_SUCCESS',
    FAILURE: 'GET_ORDER_RESPONSES_FAILURE'
  },
  SubmitOrder: {
    REQUEST: 'SUBMIT_ORDER_REQUEST',
    SUCCESS: 'SUBMIT_ORDER_SUCCESS',
    FAILURE: 'SUBMIT_ORDER_FAILURE'
  },
  ChooseLawyer: {
    REQUEST: 'CHOOSE_LAWYER_REQUEST',
    SUCCESS: 'CHOOSE_LAWYER_SUCCESS',
    FAILURE: 'CHOOSE_LAWYER_FAILURE'
  },
  RespondOrder: {
    REQUEST: 'RESPOND_ORDER_REQUEST',
    SUCCESS: 'RESPOND_ORDER_SUCCESS',
    FAILURE: 'RESPOND_ORDER_FAILURE'
  },
  GetStarterInfoForSubmit: {
    REQUEST: 'GET_STARTER_INFO_FOR_SUBMIT_REQUEST',
    SUCCESS: 'GET_STARTER_INFO_FOR_SUBMIT_SUCCESS',
    FAILURE: 'GET_STARTER_INFO_FOR_SUBMIT_FAILURE'
  }
}