export const lawyerConstants = {
  GetLawyers: {
    REQUEST: 'GET_LAWYERS_REQUEST',
    SUCCESS: 'GET_LAWYERS_SUCCESS',
    FAILURE: 'GET_LAWYERS_FAILURE'
  },

  UploadCertificate: {
    REQUEST: 'UPLOAD_CERTIFICATE_REQUEST',
    SUCCESS: 'UPLOAD_CERTIFICATE_SUCCESS',
    FAILURE: 'UPLOAD_CERTIFICATE_FAILURE'
  },

  CheckIfCertificateExists: {
    REQUEST: 'CHECK_IF_CERTIFICATE_EXISTS_REQUEST',
    SUCCESS: 'CHECK_IF_CERTIFICATE_EXISTS_SUCCESS',
    FAILURE: 'CHECK_IF_CERTIFICATE_EXISTS_FAILURE'
  },
}