export const lawyerConstants = {
  GetLawyers: {
    REQUEST: 'GET_LAWYERS_REQUEST',
    SUCCESS: 'GET_LAWYERS_SUCCESS',
    FAILURE: 'GET_LAWYERS_FAILURE'
  },

  UploadCertificate: {
    REQUEST: 'UPLOAD_CERTIFICATE_REQUEST',
    SUCCESS: 'UPLOAD_CERTIFICATE_SUCCESS',
    FAILURE: 'UPLOAD_CERTIFICATE_FAILURE'
  },

  CheckIfCertificateExists: {
    REQUEST: 'CHECK_IF_CERTIFICATE_EXISTS_REQUEST',
    SUCCESS: 'CHECK_IF_CERTIFICATE_EXISTS_SUCCESS',
    FAILURE: 'CHECK_IF_CERTIFICATE_EXISTS_FAILURE'
  },

  GetById: {
    REQUEST: 'GET_BY_ID_REQUEST',
    SUCCESS: 'GET_BY_ID_SUCCESS',
    FAILURE: 'GET_BY_ID_FAILURE'
  },

  ConfirmLawyer: {
    REQUEST: 'CONFIRM_LAWYER_REQUEST',
    SUCCESS: 'CONFIRM_LAWYER_SUCCESS',
    FAILURE: 'CONFIRM_LAWYER_FAILURE'
  },

  CheckIfLawyerCanBeConfirmed: {
    REQUEST: 'CHECK_IF_LAWYER_CAN_BE_CONFIRMED_REQUEST',
    SUCCESS: 'CHECK_IF_LAWYER_CAN_BE_CONFIRMED_SUCCESS',
    FAILURE: 'CHECK_IF_LAWYER_CAN_BE_CONFIRMED_FAILURE'
  }
}